<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'id' => 1,
                'data_type_id' => 1,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'data_type_id' => 1,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            2 => 
            array (
                'id' => 3,
                'data_type_id' => 1,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            3 => 
            array (
                'id' => 4,
                'data_type_id' => 1,
                'field' => 'password',
                'type' => 'password',
                'display_name' => 'Password',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            4 => 
            array (
                'id' => 5,
                'data_type_id' => 1,
                'field' => 'remember_token',
                'type' => 'text',
                'display_name' => 'Remember Token',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            5 => 
            array (
                'id' => 6,
                'data_type_id' => 1,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            6 => 
            array (
                'id' => 7,
                'data_type_id' => 1,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            7 => 
            array (
                'id' => 8,
                'data_type_id' => 1,
                'field' => 'avatar',
                'type' => 'image',
                'display_name' => 'Avatar',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 8,
            ),
            8 => 
            array (
                'id' => 9,
                'data_type_id' => 1,
                'field' => 'user_belongsto_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Role',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":"0","taggable":"0"}',
                'order' => 10,
            ),
            9 => 
            array (
                'id' => 10,
                'data_type_id' => 1,
                'field' => 'user_belongstomany_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Roles',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}',
                'order' => 11,
            ),
            10 => 
            array (
                'id' => 11,
                'data_type_id' => 1,
                'field' => 'settings',
                'type' => 'hidden',
                'display_name' => 'Settings',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            11 => 
            array (
                'id' => 12,
                'data_type_id' => 2,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'data_type_id' => 2,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            13 => 
            array (
                'id' => 14,
                'data_type_id' => 2,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            14 => 
            array (
                'id' => 15,
                'data_type_id' => 2,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            15 => 
            array (
                'id' => 16,
                'data_type_id' => 3,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'data_type_id' => 3,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            17 => 
            array (
                'id' => 18,
                'data_type_id' => 3,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            18 => 
            array (
                'id' => 19,
                'data_type_id' => 3,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            19 => 
            array (
                'id' => 20,
                'data_type_id' => 3,
                'field' => 'display_name',
                'type' => 'text',
                'display_name' => 'Display Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 5,
            ),
            20 => 
            array (
                'id' => 21,
                'data_type_id' => 1,
                'field' => 'role_id',
                'type' => 'text',
                'display_name' => 'Role',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 9,
            ),
            21 => 
            array (
                'id' => 75,
                'data_type_id' => 8,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            22 => 
            array (
                'id' => 76,
                'data_type_id' => 8,
                'field' => 'ci',
                'type' => 'text',
                'display_name' => 'Ci / Pasaporte',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|max:191|unique:people"},"display":{"width":4}}',
                'order' => 2,
            ),
            23 => 
            array (
                'id' => 77,
                'data_type_id' => 8,
                'field' => 'first_name',
                'type' => 'text',
                'display_name' => 'Primer Nombre',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|max:191"},"display":{"width":4}}',
                'order' => 5,
            ),
            24 => 
            array (
                'id' => 78,
                'data_type_id' => 8,
                'field' => 'middle_name',
                'type' => 'text',
            'display_name' => 'Segundo Nombre (Opcional)',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":4}}',
                'order' => 6,
            ),
            25 => 
            array (
                'id' => 79,
                'data_type_id' => 8,
                'field' => 'paternal_surname',
                'type' => 'text',
                'display_name' => 'Apeliido Paterno',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|max:191"},"display":{"width":4}}',
                'order' => 7,
            ),
            26 => 
            array (
                'id' => 80,
                'data_type_id' => 8,
                'field' => 'maternal_surname',
                'type' => 'text',
                'display_name' => 'Apeliido Materno',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":4}}',
                'order' => 8,
            ),
            27 => 
            array (
                'id' => 81,
                'data_type_id' => 8,
                'field' => 'birth_date',
                'type' => 'date',
                'display_name' => 'Fecha de Nacimiento',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":4}}',
                'order' => 3,
            ),
            28 => 
            array (
                'id' => 82,
                'data_type_id' => 8,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email / Correo electronico',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":4}}',
                'order' => 9,
            ),
            29 => 
            array (
                'id' => 83,
                'data_type_id' => 8,
                'field' => 'phone',
                'type' => 'text',
                'display_name' => 'Telefono / Celular',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":4}}',
                'order' => 10,
            ),
            30 => 
            array (
                'id' => 84,
                'data_type_id' => 8,
                'field' => 'address',
                'type' => 'text_area',
                'display_name' => 'Dirección',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":12}}',
                'order' => 12,
            ),
            31 => 
            array (
                'id' => 85,
                'data_type_id' => 8,
                'field' => 'gender',
                'type' => 'select_dropdown',
                'display_name' => 'Género',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"options":{"Masculino":"Masculino","Femenino":"Femenino"},"display":{"width":4},"validation":{"rule":"required"}}',
                'order' => 4,
            ),
            32 => 
            array (
                'id' => 86,
                'data_type_id' => 8,
                'field' => 'image',
                'type' => 'image',
                'display_name' => 'Fotografía',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"display":{"width":6},"resize":{"width":"1000","height":null},"quality":"70%","upsize":true,"thumbnails":[{"name":"medium","scale":"50%"},{"name":"small","scale":"25%"},{"name":"cropped","crop":{"width":"300","height":"250"}}]}',
                'order' => 11,
            ),
            33 => 
            array (
                'id' => 87,
                'data_type_id' => 8,
                'field' => 'status',
                'type' => 'checkbox',
                'display_name' => 'Estado',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 0,
                'details' => '{"on":"Activo","off":"Inactivo","checked":true}',
                'order' => 13,
            ),
            34 => 
            array (
                'id' => 88,
                'data_type_id' => 8,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 14,
            ),
            35 => 
            array (
                'id' => 89,
                'data_type_id' => 8,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 15,
            ),
            36 => 
            array (
                'id' => 90,
                'data_type_id' => 8,
                'field' => 'registerUser_id',
                'type' => 'text',
                'display_name' => 'RegisterUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 16,
            ),
            37 => 
            array (
                'id' => 91,
                'data_type_id' => 8,
                'field' => 'registerRole',
                'type' => 'text',
                'display_name' => 'RegisterRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 17,
            ),
            38 => 
            array (
                'id' => 92,
                'data_type_id' => 8,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 18,
            ),
            39 => 
            array (
                'id' => 93,
                'data_type_id' => 8,
                'field' => 'deleteUser_id',
                'type' => 'text',
                'display_name' => 'DeleteUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 19,
            ),
            40 => 
            array (
                'id' => 94,
                'data_type_id' => 8,
                'field' => 'deleteRole',
                'type' => 'text',
                'display_name' => 'DeleteRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 20,
            ),
            41 => 
            array (
                'id' => 95,
                'data_type_id' => 8,
                'field' => 'deleteObservation',
                'type' => 'text',
                'display_name' => 'DeleteObservation',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 21,
            ),
            42 => 
            array (
                'id' => 96,
                'data_type_id' => 1,
                'field' => 'email_verified_at',
                'type' => 'timestamp',
                'display_name' => 'Email Verified At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            43 => 
            array (
                'id' => 97,
                'data_type_id' => 1,
                'field' => 'status',
                'type' => 'text',
                'display_name' => 'Status',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 13,
            ),
            44 => 
            array (
                'id' => 98,
                'data_type_id' => 1,
                'field' => 'person_id',
                'type' => 'text',
                'display_name' => 'Person Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            45 => 
            array (
                'id' => 99,
                'data_type_id' => 1,
                'field' => 'registerUser_id',
                'type' => 'text',
                'display_name' => 'RegisterUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 14,
            ),
            46 => 
            array (
                'id' => 100,
                'data_type_id' => 1,
                'field' => 'registerRole',
                'type' => 'text',
                'display_name' => 'RegisterRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 15,
            ),
            47 => 
            array (
                'id' => 101,
                'data_type_id' => 1,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 16,
            ),
            48 => 
            array (
                'id' => 102,
                'data_type_id' => 1,
                'field' => 'deleteUser_id',
                'type' => 'text',
                'display_name' => 'DeleteUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 17,
            ),
            49 => 
            array (
                'id' => 103,
                'data_type_id' => 1,
                'field' => 'deleteRole',
                'type' => 'text',
                'display_name' => 'DeleteRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 18,
            ),
            50 => 
            array (
                'id' => 104,
                'data_type_id' => 1,
                'field' => 'deleteObservation',
                'type' => 'text',
                'display_name' => 'DeleteObservation',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 19,
            ),
            51 => 
            array (
                'id' => 105,
                'data_type_id' => 9,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 1,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            52 => 
            array (
                'id' => 106,
                'data_type_id' => 9,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Registrado',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            53 => 
            array (
                'id' => 107,
                'data_type_id' => 9,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            54 => 
            array (
                'id' => 108,
                'data_type_id' => 9,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Categoría',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"display":{"width":12}}',
                'order' => 2,
            ),
            55 => 
            array (
                'id' => 109,
                'data_type_id' => 9,
                'field' => 'observation',
                'type' => 'text_area',
                'display_name' => 'Observación / Descripción',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"display":{"width":12}}',
                'order' => 3,
            ),
            56 => 
            array (
                'id' => 110,
                'data_type_id' => 9,
                'field' => 'status',
                'type' => 'checkbox',
                'display_name' => 'Estado',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 0,
                'details' => '{"on":"Activo","off":"Inactivo","checked":true}',
                'order' => 4,
            ),
            57 => 
            array (
                'id' => 111,
                'data_type_id' => 9,
                'field' => 'registerUser_id',
                'type' => 'text',
                'display_name' => 'RegisterUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            58 => 
            array (
                'id' => 112,
                'data_type_id' => 9,
                'field' => 'registerRole',
                'type' => 'text',
                'display_name' => 'RegisterRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            59 => 
            array (
                'id' => 113,
                'data_type_id' => 9,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            60 => 
            array (
                'id' => 114,
                'data_type_id' => 9,
                'field' => 'deleteUser_id',
                'type' => 'text',
                'display_name' => 'DeleteUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            61 => 
            array (
                'id' => 115,
                'data_type_id' => 9,
                'field' => 'deleteRole',
                'type' => 'text',
                'display_name' => 'DeleteRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            62 => 
            array (
                'id' => 116,
                'data_type_id' => 9,
                'field' => 'deleteObservation',
                'type' => 'text',
                'display_name' => 'DeleteObservation',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            63 => 
            array (
                'id' => 117,
                'data_type_id' => 10,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 1,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            64 => 
            array (
                'id' => 118,
                'data_type_id' => 10,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Categoría',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|max:191"},"display":{"width":4}}',
                'order' => 2,
            ),
            65 => 
            array (
                'id' => 119,
                'data_type_id' => 10,
                'field' => 'observation',
                'type' => 'text_area',
                'display_name' => 'Descripción / Detalle',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"display":{"width":12}}',
                'order' => 3,
            ),
            66 => 
            array (
                'id' => 120,
                'data_type_id' => 10,
                'field' => 'status',
                'type' => 'text',
                'display_name' => 'Estado',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 0,
                'details' => '{"on":"Activo","off":"Inactivo","checked":true}',
                'order' => 4,
            ),
            67 => 
            array (
                'id' => 121,
                'data_type_id' => 10,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Registrado',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            68 => 
            array (
                'id' => 122,
                'data_type_id' => 10,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            69 => 
            array (
                'id' => 123,
                'data_type_id' => 10,
                'field' => 'registerUser_id',
                'type' => 'text',
                'display_name' => 'RegisterUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            70 => 
            array (
                'id' => 124,
                'data_type_id' => 10,
                'field' => 'registerRole',
                'type' => 'text',
                'display_name' => 'RegisterRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            71 => 
            array (
                'id' => 125,
                'data_type_id' => 10,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            72 => 
            array (
                'id' => 126,
                'data_type_id' => 10,
                'field' => 'deleteUser_id',
                'type' => 'text',
                'display_name' => 'DeleteUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            73 => 
            array (
                'id' => 127,
                'data_type_id' => 10,
                'field' => 'deleteRole',
                'type' => 'text',
                'display_name' => 'DeleteRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            74 => 
            array (
                'id' => 128,
                'data_type_id' => 10,
                'field' => 'deleteObservation',
                'type' => 'text',
                'display_name' => 'DeleteObservation',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            75 => 
            array (
                'id' => 129,
                'data_type_id' => 11,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 1,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            76 => 
            array (
                'id' => 130,
                'data_type_id' => 11,
                'field' => 'itemCategory_id',
                'type' => 'text',
                'display_name' => 'ItemCategory Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            77 => 
            array (
                'id' => 131,
                'data_type_id' => 11,
                'field' => 'image',
                'type' => 'image',
                'display_name' => 'Imagen',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"display":{"width":6},"resize":{"width":"1000","height":null},"quality":"70%","upsize":true,"thumbnails":[{"name":"medium","scale":"50%"},{"name":"small","scale":"25%"},{"name":"cropped","crop":{"width":"300","height":"250"}}]}',
                'order' => 5,
            ),
            78 => 
            array (
                'id' => 132,
                'data_type_id' => 11,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Productos / Items',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|max:191"},"display":{"width":4}}',
                'order' => 4,
            ),
            79 => 
            array (
                'id' => 134,
                'data_type_id' => 11,
                'field' => 'observation',
                'type' => 'text_area',
                'display_name' => 'Observación / Descripción',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"display":{"width":12}}',
                'order' => 6,
            ),
            80 => 
            array (
                'id' => 136,
                'data_type_id' => 11,
                'field' => 'status',
                'type' => 'text',
                'display_name' => 'Status',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            81 => 
            array (
                'id' => 137,
                'data_type_id' => 11,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Registrado',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            82 => 
            array (
                'id' => 138,
                'data_type_id' => 11,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            83 => 
            array (
                'id' => 139,
                'data_type_id' => 11,
                'field' => 'registerUser_id',
                'type' => 'text',
                'display_name' => 'RegisterUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            84 => 
            array (
                'id' => 140,
                'data_type_id' => 11,
                'field' => 'registerRole',
                'type' => 'text',
                'display_name' => 'RegisterRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            85 => 
            array (
                'id' => 141,
                'data_type_id' => 11,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            86 => 
            array (
                'id' => 142,
                'data_type_id' => 11,
                'field' => 'deleteUser_id',
                'type' => 'text',
                'display_name' => 'DeleteUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 13,
            ),
            87 => 
            array (
                'id' => 143,
                'data_type_id' => 11,
                'field' => 'deleteRole',
                'type' => 'text',
                'display_name' => 'DeleteRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 14,
            ),
            88 => 
            array (
                'id' => 144,
                'data_type_id' => 11,
                'field' => 'deleteObservation',
                'type' => 'text',
                'display_name' => 'DeleteObservation',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 15,
            ),
            89 => 
            array (
                'id' => 145,
                'data_type_id' => 11,
                'field' => 'item_belongsto_item_category_relationship',
                'type' => 'relationship',
                'display_name' => 'Categoría',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":4},"model":"App\\\\Models\\\\ItemCategory","table":"item_categories","type":"belongsTo","column":"itemCategory_id","key":"id","label":"name","pivot_table":"cashiers","pivot":"0","taggable":"0"}',
                'order' => 3,
            ),
            90 => 
            array (
                'id' => 146,
                'data_type_id' => 12,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 1,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            91 => 
            array (
                'id' => 147,
                'data_type_id' => 12,
                'field' => 'type',
                'type' => 'select_dropdown',
                'display_name' => 'Tipo',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"options":{"Normal":"Normal","Vip":"Vip"},"display":{"width":4},"validation":{"rule":"required"}}',
                'order' => 2,
            ),
            92 => 
            array (
                'id' => 148,
                'data_type_id' => 12,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nombre',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|max:191"},"display":{"width":4}}',
                'order' => 3,
            ),
            93 => 
            array (
                'id' => 149,
                'data_type_id' => 12,
                'field' => 'observation',
                'type' => 'text_area',
                'display_name' => 'Descripción / Detalle',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":12}}',
                'order' => 5,
            ),
            94 => 
            array (
                'id' => 150,
                'data_type_id' => 12,
                'field' => 'status',
                'type' => 'checkbox',
                'display_name' => 'Estado',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => 'null',
                'order' => 6,
            ),
            95 => 
            array (
                'id' => 151,
                'data_type_id' => 12,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Registrado',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            96 => 
            array (
                'id' => 152,
                'data_type_id' => 12,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            97 => 
            array (
                'id' => 153,
                'data_type_id' => 12,
                'field' => 'registerUser_id',
                'type' => 'text',
                'display_name' => 'RegisterUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            98 => 
            array (
                'id' => 154,
                'data_type_id' => 12,
                'field' => 'registerRole',
                'type' => 'text',
                'display_name' => 'RegisterRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            99 => 
            array (
                'id' => 155,
                'data_type_id' => 12,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            100 => 
            array (
                'id' => 156,
                'data_type_id' => 12,
                'field' => 'deleteUser_id',
                'type' => 'text',
                'display_name' => 'DeleteUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            101 => 
            array (
                'id' => 157,
                'data_type_id' => 12,
                'field' => 'deleteRole',
                'type' => 'text',
                'display_name' => 'DeleteRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 13,
            ),
            102 => 
            array (
                'id' => 158,
                'data_type_id' => 12,
                'field' => 'deleteObservation',
                'type' => 'text',
                'display_name' => 'DeleteObservation',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 14,
            ),
            103 => 
            array (
                'id' => 159,
                'data_type_id' => 12,
                'field' => 'image',
                'type' => 'image',
                'display_name' => 'Imagen',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"display":{"width":6},"resize":{"width":"1000","height":null},"quality":"70%","upsize":true,"thumbnails":[{"name":"medium","scale":"50%"},{"name":"small","scale":"25%"},{"name":"cropped","crop":{"width":"300","height":"250"}}]}',
                'order' => 4,
            ),
        ));
        
        
    }
}